### ISSUE TITLE
col.names argument not used in write.csv.raw

### ISSUE THREAD

**Issue by andrewuhl** [s-u/iotools#26]
```r
write.csv.raw = function(x, file = "", append = FALSE, sep = ",", nsep="\t",
                          col.names = TRUE, fileEncoding = "") {
  if (is.character(file)) {
    file <- if (nzchar(fileEncoding))
            file(file, ifelse(append, "ab", "wb"), encoding = fileEncoding)
        else file(file, ifelse(append, "ab", "wb"))
    on.exit(close(file))
  } else if (!isOpen(file, "w")) {
    open(file, "wb")
    on.exit(close(file))
  }

  r = as.output(x, sep = sep, nsep=nsep)
  writeBin(r, con=file)
}
```

**Comment by gregorybooma** [comment]
Looks like append and fileEncoding are also left out. fileEncoding doesn't apply for me, but having col.names and append would be great...

**Comment by demydd** [comment]
It looks to work well. 
At least in my case http://stackoverflow.com/questions/35295320/the-fastest-way-to-write-csv-file-by-write-csv-raw-iotools-package.
It would be nice to add ability to define decimal sign like ' dec="," ' .

**Comment by demydd** [comment]
Comparison of 'write.csv.raw' and other write-methods (details see at http://stackoverflow.com/questions/35295320/the-fastest-way-to-write-csv-file-by-write-csv-raw-iotools-package):
> system.time(write.csv.raw(n,"test.csv",sep=";",append=TRUE))
   user  system elapsed 
  15.61    1.17   21.92 
> system.time(write.table(n,"test.csv",sep=";",row.names=FALSE,dec=","))
   user  system elapsed 
  63.25    1.20   64.60 
> system.time(write.csv2(n,"test.csv",row.names=FALSE))
   user  system elapsed 
  63.71    1.28   65.38 
> system.time(write_csv(n, "test.csv", na = "NA"))
   user  system elapsed 
 136.75    3.60  141.24
