### ISSUE TITLE
How to compile it?

### ISSUE THREAD

**Issue by yetian1** [s-u/iotools#29]
I git clone https://github.com/s-u/iotools.git, but I can not make it?
Would you help to do ?

**Comment by statsmaths** [comment]
In order to build R packages, you do the following:
```
R CMD build iotools
R CMD INSTALL iotools_0.2-2.tar.gz
```
Though you can also install directly from within R using the devtools package: `devtools::install_github("s-u/iotools")`, or installing the stable version from CRAN.
