### ISSUE TITLE
problem with chunk.tapply

### ISSUE THREAD

**Issue by talegari** [s-u/iotools#31]
**Purpose**: Split the iris dataframe by the column 'Species' and then count the number of rows.

**Problem**: try using `chunk.tapply` seems to gives an unexpected result

Plain way, 
```r
sapply(split(iris, iris$Species), nrow)
```

yields the (named)vector `c(50, 50, 50)`.

----

Try to reproduce this with `chunk.tapply`:

```r
write.table(iris[, c(5,1:4)]
            , "iris.csv"
            , row.names = FALSE
            , sep = ","
            , col.names = FALSE)

View(read.csv("iris.csv", header = FALSE))

library("iotools")
chunk.tapply(input = "iris.csv"
             , FUN = function(x){
                       df <- dstrsplit(x
                                 , col_types = c("character"
                                                 , rep("numeric", 4))
                                 , sep = ","
                                 )
                       # print(df) # to observe whats happening
                       nrow(df)
                       }
             , CH.MERGE =  c
             , sep = ",")
```
 yields `c(100, 50)`. Printing the dataframes after `dstrsplit` shows that rows corresponding to 'setosa' and 'versicolor' aren't considered as different dataframes. Is there something wrong with what I am doing?

iotools version: 0.1-12(the one on cran)

**Comment by s-u** [comment]
Chunking creates chunks that are guaranteed to not split keys, but they are not creating chunks that have only one key - there can be one or more keys. To illustrate on your example:

```r
> res <- chunk.tapply(input = "iris.csv", function(x) {
+   df <- dstrsplit(x, c(list(""), rep(list(1), 4)), sep=',')
+   cat("-- chunk --\n")
+   print(table(df[[1]]))
+ }, sep=",", CH.MERGE=c)
-- chunk --

    "setosa" "versicolor" 
          50           50 
-- chunk --

"virginica" 
         50 
> res
    "setosa" "versicolor"  "virginica" 
          50           50           50 
``` 
so the first chunk contains both "setosa" and "versicolor" which the last chunk has only "virginica".
